Integrate with tracy-client
Wumpf/wgpu-profiler pull request #35
Opened 2023-08-01 02:04 UTC by cwfitzgerald

Closes #15 

Depends on https://github.com/nagisa/rust_tracy_client/pull/41

This is working and ready for review, just can't be merged until the above pull request is finalized.

2023-08-01 14:25 UTC, Imberflur requested changes
:heart: Thank you for getting this working! I'm excited to be able to use it.

The changes lgtm, with two minor notes in the examples/tests.

2023-08-01 14:25 UTC, Imberflur commented on tests/dropped_frame_handling.rs
> +    let mut profiler = wgpu_profiler::GpuProfiler::new(&adapter, &device, &queue, 4);
I think this test specifically uses `1` here so that a frame will be "dropped" below.

2023-08-01 14:25 UTC, Imberflur commented on examples/demo.rs
> +        backends: wgpu::Backends::DX12,
It looks like this was changed for testing and needs to be switched back to `all` or at least to include vulkan.

2023-08-02 01:39 UTC, cwfitzgerald commented
Thanks for catching these, fixed!

2023-08-02 08:04 UTC, Wumpf approved these changes
awesome! Thanks @cwfitzgerald  and thanks @Imberflur for thorough review
New release incoming!

2023-08-02 08:04 UTC, merged